export type GalleryCategory = 'outdoors' | 'friends' | 'rest' | 'portraits' | 'cuddles' | 'play'

interface GalleryPhoto {
  id: number
  src: string
  alt: string
  categories: readonly GalleryCategory[]
  width: number
  height: number
}

const moments: readonly [number, string, readonly GalleryCategory[], number?, number?][] = [
  [
    225,
    'Heller Hund mit Geschirr sitzt auf einem sonnigen Waldweg',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    234,
    'Ein dreifarbiger und ein kleiner weißer Hund schauen auf einem gepflasterten Weg in die Kamera',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    201,
    'Braun-weißer Hund schläft auf einer grauen Decke auf dem Fliesenboden',
    ['rest'],
    1200,
    1600,
  ],
  [
    219,
    'Brauner lockiger Hund trägt beim Spaziergang einen gelben Regenmantel',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    247,
    'Vier Hunde mit unterschiedlichem Fell liegen nebeneinander auf einer grünen Wiese',
    ['friends', 'portraits'],
    1600,
    1200,
  ],
  [
    202,
    'Braun-weißer lockiger Hund schläft auf dem Rücken in einem hellen Hundebett',
    ['rest'],
    1200,
    1600,
  ],
  [
    215,
    'Ein brauner und ein heller Hund sitzen und liegen gemeinsam neben einem Wassernapf im Garten',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    203,
    'Heller Hund mit Schneeflocken auf der Nase beim Spaziergang im Schnee',
    ['outdoors', 'portraits'],
    900,
    1600,
  ],
  [
    204,
    'Heller lockiger Hund schaut im Wohnzimmer mit schräg gelegtem Kopf in die Kamera',
    ['portraits'],
    1200,
    1600,
  ],
  [
    205,
    'Zwei Hunde schlafen nebeneinander auf einer Decke und in einem Hundebett',
    ['rest', 'friends'],
    1200,
    1600,
  ],
  [
    206,
    'Dreifarbiger Hund schläft neben einer bunten Decke auf einem grünen Sessel',
    ['rest'],
    1200,
    1600,
  ],
  [207, 'Heller Hund schläft mit dem Kopf auf einem weichen Teppich', ['rest'], 1200, 1600],
  [
    208,
    'Schwarzer lockiger Hund lässt sich auf dem Rücken liegend am Bauch kraulen',
    ['portraits', 'cuddles'],
    910,
    1600,
  ],
  [209, 'Brauner lockiger Hund ruht mit dem Kopf auf einer grauen Decke', ['rest'], 900, 1600],
  [
    210,
    'Heller Hund schläft auf einem grünen Sofa hinter einem Tisch mit Tulpen',
    ['rest'],
    1200,
    1600,
  ],
  [211, 'Heller lockiger Hund mit rosa Halstuch steht im Wohnzimmer', ['portraits'], 900, 1600],
  [
    212,
    'Brauner Hund schaut mit den Vorderpfoten über die Lehne eines grünen Sessels',
    ['portraits'],
    1200,
    1600,
  ],
  [
    213,
    'Heller Hund legt Kopf und Vorderpfote auf einen Schoß',
    ['portraits', 'cuddles'],
    1200,
    1600,
  ],
  [
    214,
    'Nasser heller Hund schaut draußen neben einem Wassernapf nach oben',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    216,
    'Heller Hund schläft mit dem Kopf auf dem Rand eines grauen Hundebetts',
    ['rest'],
    1200,
    1600,
  ],
  [217, 'Heller Hund mit blauer Fliege sitzt auf einem grünen Sessel', ['portraits'], 1200, 1600],
  [
    218,
    'Heller Hund liegt neben einer Person unter einer weißen Bettdecke',
    ['portraits', 'cuddles'],
    1200,
    1600,
  ],
  [
    220,
    'Ein schwarzer und ein heller Hund ruhen in einem Sonnenstreifen auf dem Küchenboden',
    ['rest', 'friends'],
    1200,
    1600,
  ],
  [221, 'Kleiner heller Hund liegt mit einem Kaustick in einem runden Hundebett', [], 1200, 1600],
  [
    222,
    'Ein schwarzer und ein heller Hund schlafen an der offenen Terrassentür',
    ['rest', 'friends'],
    1200,
    1600,
  ],
  [
    223,
    'Ein brauner und ein weißer Hund schlafen gemeinsam in einem grauen Hundebett',
    ['rest', 'friends'],
    1200,
    1600,
  ],
  [
    224,
    'Ein kleiner braun-weißer und ein großer heller Hund schauen beim Spaziergang nach oben',
    ['friends', 'portraits', 'outdoors'],
    1200,
    1600,
  ],
  [226, 'Kleiner brauner Hund schaut zwischen weißen Bettdecken hervor', ['portraits'], 1200, 1600],
  [
    227,
    'Heller Hund schläft auf einer bunten Decke auf der sonnigen Terrasse',
    ['rest'],
    1200,
    1600,
  ],
  [
    228,
    'Heller Hund ruht neben einem Kuscheltier und einer Person auf einem Bett',
    ['rest', 'cuddles'],
    1200,
    1600,
  ],
  [
    229,
    'Drei Hunde mit weißem, schwarzem und braunem Fell sind gemeinsam an der Leine unterwegs',
    ['friends', 'outdoors'],
    1200,
    1600,
  ],
  [
    230,
    'Mehrere angeleinte Hunde begegnen sich auf einem sonnigen Gehweg',
    ['friends', 'outdoors'],
    1200,
    1600,
  ],
  [
    231,
    'Heller Hund schläft ausgestreckt auf dem Fliesenboden vor einem grünen Sofa',
    ['rest'],
    1200,
    1600,
  ],
  [
    232,
    'Brauner Hund ruht mit dem Kopf auf einem Schoß, während ein heller Hund auf dem Sofa schläft',
    ['rest', 'portraits', 'cuddles', 'friends'],
    1200,
    1600,
  ],
  [233, 'Heller Hund hält einen Kaustick zwischen den Vorderpfoten auf einer Decke', [], 736, 1600],
  [235, 'Kleiner weißer lockiger Hund sitzt auf einem Schoß', ['portraits', 'cuddles'], 1600, 1200],
  [
    236,
    'Schwarzer Hund mit rotem Halsband schläft auf einer rosa Hundematte',
    ['rest'],
    1200,
    1600,
  ],
  [
    237,
    'Drei angeleinte Hunde schauen bei einem gemeinsamen Spaziergang nach oben',
    ['friends', 'portraits', 'outdoors'],
    1200,
    1600,
  ],
  [
    238,
    'Ein heller lockiger und ein brauner Hund ruhen gemeinsam auf dem Sofa',
    ['rest', 'friends'],
    1200,
    1600,
  ],
  [
    239,
    'Schwarz-brauner rauhaariger Hund schläft auf einem grauen Hundekissen',
    ['rest'],
    1200,
    1600,
  ],
  [
    240,
    'Dreifarbiger Hund liegt mit angehobenen Pfoten auf dem Rücken im Gras',
    ['portraits', 'play'],
    1200,
    1600,
  ],
  [
    241,
    'Ein kleiner weißer Hund und ein dreifarbiger Terrier schauen im Wohnzimmer nach oben',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    242,
    'Kleiner weißer lockiger Hund schläft ausgestreckt vor der Küchenzeile',
    ['rest'],
    1200,
    1600,
  ],
  [
    243,
    'Dreifarbiger Terrier schläft eingerollt in einem runden grauen Hundebett',
    ['rest'],
    1200,
    1600,
  ],
  [
    244,
    'Dunkler rauhaariger Hund schläft auf dem Fliesenboden im Wohnzimmer',
    ['rest'],
    1200,
    1600,
  ],
  [
    245,
    'Heller Hund schläft zusammengerollt in einer offenen weichen Hundebox',
    ['rest'],
    1200,
    1600,
  ],
  [
    246,
    'Drei Hunde liegen gemeinsam im Gras und schauen im Abendlicht zurück',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    248,
    'Kleiner brauner Hund liegt auf dem Rücken im Gras und schaut nach oben',
    ['portraits', 'play'],
    1200,
    1600,
  ],
  [249, 'Braun-weißer Hund schläft im Gras neben einem kleinen Hundepool', ['rest'], 1200, 1600],
  [
    250,
    'Brauner lockiger Hund ruht mit dem Kopf auf dem Boden unter einem Stuhl',
    ['rest'],
    1200,
    1600,
  ],
  [
    251,
    'Schwarzer Hund mit rotem Halsband ruht ausgestreckt auf dem Fliesenboden',
    ['rest'],
    1200,
    1600,
  ],
  [
    252,
    'Schwarz-brauner Hund schläft mit geschlossenen Augen auf einem Schoß',
    ['rest', 'cuddles'],
    1200,
    1600,
  ],
  [
    253,
    'Zwei braune Hunde schlafen nebeneinander auf einer Decke und einem Hundekissen',
    ['rest', 'friends'],
    1600,
    1200,
  ],
  [
    254,
    'Dunkler gestromter Hund schläft mit dem Kopf auf dem Rand eines Hundebetts',
    ['rest'],
    1200,
    1600,
  ],
  [
    115,
    'Braun-weißer Hund schaut vor rosa Hortensien nach oben',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    101,
    'Drei Hunde verbringen gemeinsam Zeit auf einer grünen Wiese',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [119, 'Heller Hund liegt entspannt auf dem Rücken auf einem grünen Sofa', ['rest'], 1200, 1600],
  [
    114,
    'Ein schwarzer und ein brauner lockiger Hund stehen nebeneinander im Wald',
    ['friends', 'portraits', 'outdoors'],
    1200,
    1600,
  ],
  [
    102,
    'Ein heller Hund lässt sich auf der Wiese streicheln, daneben sitzt ein kleiner brauner Hund',
    ['friends', 'portraits', 'cuddles'],
    1600,
    1200,
  ],
  [
    103,
    'Mehrere Hunde versammeln sich vor blühenden Hortensien auf der Terrasse',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    104,
    'Dreifarbiger Hund mit blauem Geschirr im Sonnenschein',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    105,
    'Ein braun-weißer und ein schwarzer lockiger Hund sitzen gemeinsam auf einer Treppe',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    106,
    'Drei Hunde schauen von einer Rasenfläche neugierig in die Kamera',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [107, 'Zwei lockige Hunde erkunden gemeinsam den Garten', ['friends', 'play'], 909, 1600],
  [
    108,
    'Brauner Hund mit langen Ohren schaut auf der Wiese nach oben',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    109,
    'Ein heller und ein schwarzer Hund machen eine Pause auf der Terrasse',
    ['rest', 'friends'],
    1200,
    1600,
  ],
  [110, 'Zwei Hunde ruhen im Schatten auf der Terrasse', ['rest', 'friends'], 1200, 1600],
  [111, 'Schwarzer Hund legt den Kopf entspannt auf ein braunes Kissen', ['rest'], 1200, 1600],
  [
    112,
    'Brauner Hund mit heller Brust und blauer Leine auf einem Waldweg',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    113,
    'Zwei Hunde schlafen zusammen in einem hellen Hundebett',
    ['rest', 'cuddles', 'friends'],
    1200,
    1600,
  ],
  [
    116,
    'Ein braun-weißer und ein schwarzer Hund schauen bei einem Waldspaziergang nach oben',
    ['friends', 'portraits', 'outdoors'],
    1200,
    1600,
  ],
  [
    117,
    'Zwei braune Hunde schlafen eng aneinandergekuschelt in ihrem Bett',
    ['rest', 'cuddles', 'friends'],
    1200,
    1600,
  ],
  [
    118,
    'Ein heller und zwei schwarze Hunde verbringen gemeinsam Zeit im Wohnzimmer',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    120,
    'Drei Hunde schauen im Wohnzimmer neugierig in die Kamera',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    121,
    'Drei angeleinte Hunde bei einem gemeinsamen Spaziergang auf einem gepflasterten Weg',
    ['friends', 'portraits', 'outdoors'],
    1200,
    1600,
  ],
  [122, 'Dreifarbiger Hund schläft mit der Schnauze auf einer Decke', ['rest'], 1200, 1600],
  [
    123,
    'Zwei Hunde liegen mit den Köpfen nebeneinander auf einem Hundekissen',
    ['rest', 'cuddles', 'friends'],
    1200,
    1600,
  ],
  [124, 'Heller Hund kuschelt sich auf einem Schoß ein', ['rest', 'cuddles'], 1200, 1600],
  [
    125,
    'Dunkelbrauner Hund mit Geschirr auf einem sonnigen Gehweg',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    126,
    'Drei Hunde sitzen hintereinander auf einer sonnigen Wiese',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    127,
    'Ein großer dunkelbrauner und ein kleiner schwarz-brauner Hund auf der Terrasse',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [
    128,
    'Dunkelbrauner Hund sitzt an der Leine auf einem gepflasterten Weg',
    ['outdoors', 'portraits'],
    1200,
    1600,
  ],
  [
    129,
    'Schwarz-brauner rauhaariger Hund im Sonnenschein, dahinter ein weiterer Hund auf der Wiese',
    ['friends', 'portraits'],
    1200,
    1600,
  ],
  [2, 'Heller Hund vor einem Strauch mit rosa Blüten', ['outdoors', 'portraits']],
  [
    19,
    'Zwei Hunde sitzen gemeinsam auf einem Baumstamm im Wald',
    ['friends', 'portraits', 'outdoors'],
  ],
  [10, 'Ein Hund sitzt auf einem grünen Sessel', ['portraits']],
  [
    1,
    'Zwei braune Hunde schauen auf einem Waldweg in die Kamera',
    ['friends', 'portraits', 'outdoors'],
  ],
  [9, 'Schwarzer lockiger Hund vor kleinen weißen Blumen', ['outdoors', 'portraits']],
  [27, 'Eine Gruppe Hunde bei einer gemeinsamen Pause im Wald', ['friends', 'outdoors']],
  [15, 'Ein heller lockiger Hund schläft eingerollt in seinem Hundebett', ['rest']],
  [
    35,
    'Zwei Hunde sitzen im Sonnenschein auf einem Baumstumpf',
    ['friends', 'portraits', 'outdoors'],
  ],
  [
    3,
    'Brauner Hund steht mit den Pfoten in einem kleinen Wasserbecken',
    ['outdoors', 'portraits', 'play'],
  ],
  [4, 'Schwarzer Hund sitzt im sonnigen Wald', ['outdoors', 'portraits']],
  [5, 'Zwei Hunde liegen nebeneinander auf der Terrasse', ['rest', 'friends']],
  [6, 'Dreifarbiger Hund schaut auf der Terrasse nach oben', ['outdoors', 'portraits']],
  [7, 'Schwarz-brauner Hund sitzt vor rosa Blumen', ['outdoors', 'portraits']],
  [8, 'Ein heller und ein schwarzer Hund warten gemeinsam im Flur', ['friends', 'portraits']],
  [11, 'Braun-weißer Hund schaut aus dem grünen Gebüsch', ['outdoors', 'portraits']],
  [12, 'Zwei Hunde ruhen zusammen auf einer Decke', ['rest', 'cuddles', 'friends']],
  [13, 'Schwarz-brauner Hund auf einem verschneiten Weg', ['outdoors', 'portraits']],
  [14, 'Weißer Hund läuft über eine grüne Wiese', ['outdoors', 'play']],
  [16, 'Drei Hunde schauen neugierig aus dem Flur in die Kamera', ['friends', 'portraits']],
  [17, 'Dreifarbiger Hund genießt einen Sonnenplatz auf der Terrasse', ['rest']],
  [18, 'Braun-weißer Hund beim Fressen auf der Terrasse', []],
  [
    20,
    'Zwei Hunde auf einem mit buntem Herbstlaub bedeckten Weg',
    ['friends', 'portraits', 'outdoors'],
  ],
  [21, 'Heller Hund liegt auf einer Wiese', ['portraits']],
  [23, 'Drei angeleinte Hunde sind gemeinsam unterwegs', ['friends', 'outdoors']],
  [24, 'Mehrere Hunde versammeln sich auf der Terrasse', ['friends', 'portraits']],
  [
    25,
    'Ein brauner und ein dunkelbrauner Hund schauen nebeneinander nach oben',
    ['friends', 'portraits'],
  ],
  [26, 'Schwarzer Hund lässt sich auf der Terrasse am Kinn streicheln', ['cuddles']],
  [
    28,
    'Kleiner braun-weißer Hund mit orangefarbener Leine auf einem Weg',
    ['outdoors', 'portraits'],
  ],
  [
    29,
    'Ein schwarzer und ein kleiner weißer Hund beim gemeinsamen Spaziergang',
    ['friends', 'portraits', 'outdoors'],
  ],
  [30, 'Drei angeleinte Hunde erkunden einen Waldweg', ['friends', 'portraits', 'outdoors']],
  [31, 'Brauner Hund mit Geschirr im Sonnenschein', ['outdoors', 'portraits']],
  [32, 'Brauner Hund bei einer Pause auf dem Waldweg', ['outdoors', 'portraits']],
  [33, 'Dreifarbiger Hund zwischen Blättern und Sonnenflecken', ['outdoors', 'portraits']],
  [
    34,
    'Zwei Hunde schauen auf einem laubbedeckten Waldweg nach oben',
    ['friends', 'portraits', 'outdoors'],
  ],
  [36, 'Heller Hund mit blauer Leine am Wegesrand', ['outdoors', 'portraits']],
  [37, 'Zwei Hunde an der Leine vor einem Gebüsch', ['friends', 'portraits', 'outdoors']],
  [
    38,
    'Ein braun-weißer und ein schwarzer Hund bei einem Ausflug',
    ['friends', 'portraits', 'outdoors'],
  ],
]

export const GALLERY_PHOTOS: readonly GalleryPhoto[] = moments.map(
  ([id, alt, categories, width, height]) => ({
    id,
    src: `/einblicke/hundemoment-${String(id).padStart(2, '0')}.webp`,
    alt,
    categories,
    width: width ?? (id === 27 ? 680 : id === 23 ? 510 : id === 14 ? 290 : 382),
    height: height ?? 510,
  }),
)
